swiftmailer:
    #url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport:  smtp
    encryption: ssl
    host:       mail.smtp2go.com
    port:       465
    username:   browseinhouse@gmail.com
    password:   GiEjMx84Bokg
    auth-mode:  login
