swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    #transport:  gmail
    #username:   browseinhouse@gmail.com
    #password:   pepiniere2018
    #host:       localhost
    #port:       2525
    #e#ncryption: ssl
    #auth-mode:  oauth
    #stream_options:
        #ssl:
            ##allow_self_signed: true
            #verify_peer: false
            #verify_peer_name: false
